### ISSUE TITLE
Error when deploying to Android device

### ISSUE THREAD

**Issue by derwaldgeist** [JimmyMakesThings/cordova-plugin-digits#6]
I tried to integrate this plugin into a MeteorJS based Cordova app. The build seems to work, but once the app is launched on the device, I get the following error:

```
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform Android with options --device:
   Error: Command failed:                     
   /Users/waldgeist/Documents/Development/htdocs/aiddogs/webapp/.meteor/local/cordova-build/platforms/android/cordova/run
   --device
   Note: Some input files use or override a deprecated API.
   Note: Recompile with -Xlint:deprecation for details.
   Note: Some input files use or override a deprecated API.
   Note: Recompile with -Xlint:deprecation for details.
   
   FAILURE: Build failed with an exception.
   
   * What went wrong:
   Execution failed for task ':fabricGenerateResourcesArmv7Debug'.
   > Crashlytics Developer Tools error.
   
   * Try:
   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
   

   /Users/waldgeist/Documents/Development/htdocs/aiddogs/webapp/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
   throw e;
   ^
   Error code 1 for command:
   /Users/waldgeist/Documents/Development/htdocs/aiddogs/webapp/.meteor/local/cordova-build/platforms/android/gradlew
   with args:
   cdvBuildDebug,-b,/Users/waldgeist/Documents/Development/htdocs/aiddogs/webapp/.meteor/local/cordova-build/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
   at ChildProcess.exitCallback
   (/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.10.195lp5z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/processes.js:150:21)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)
   
                                              
ExitWithCode:1
```
Meteor 1.2 is using Cordova 5.2.0, which includes Cordova Android 4.1 and Cordova iOS 3.9.

**Comment by derwaldgeist** [comment]
I re-ran it in verbose log mode and got this:
```
java.lang.IllegalArgumentException: Crashlytics found an invalid API key: <my>. 
Check the Crashlytics plugin to make sure that the application has been added successfully! 
Contact support@fabric.io for assistance.
	at com.crashlytics.tools.android.DeveloperTools.processApiKey(DeveloperTools.java:326)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:466)
	at com.crashlytics.tools.android.DeveloperTools.processArgs(DeveloperTools.java:299)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
```
Obviously, there's a problem with my API key. I tried both the "API Key" and the "Consumer Key" I got from Fabric.io for Digits, but neither is accepted. Do I need a separate key for Crashlytics?

**Comment by derwaldgeist** [comment]
Ok. It worked after I created a Crashlytics API key and used this as the "API key" (instead of the Digits API Key". I recommend to document this.

**Comment by ruifilipeasilva** [comment]
How did you resolved this issue?
I'm still facing it. Can you help me please?
Thank you

**Comment by derwaldgeist** [comment]
Hi @ruifilipeasilva, I solved it by creating a "Crashlytics API key" via the Fabric.io website. Then, I provided this key as the "Digits API key" in the Cordova config and it worked.

**Comment by ruifilipeasilva** [comment]
@derwaldgeist Can you show me your cordova config file please?

**Comment by ruifilipeasilva** [comment]
@derwaldgeist Ok thank you for your help :)
